import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Header from "../components/Header";
import Button from "../components/Button";
import FeatureCard from "../components/FeatureCard"; // ⭐ IMPORTED
import useAuth from "../hooks/useAuth";
import {
  Github, Linkedin, Instagram, Code,
  Target,
  Rocket,
  TrendingUp,
  CheckCircle,
  Award,
  Users,
} from "lucide-react";
import { FaWhatsapp } from "react-icons/fa";

// IMPORT IMAGES
import feature1 from "../assets/featurecard1.png";
import feature2 from "../assets/featurecard2.png";
import feature3 from "../assets/featurecard3.png";
import feature4 from "../assets/featurecard4.png";
import feature5 from "../assets/featurecard5.png";
import feature6 from "../assets/featurecard6.png";

const features = [
  {
    title: "AI Roadmap Generator",
    desc: "Build your personalized learning path with AI assistance tailored to your career goals.",
    href: "/roadmaps",
    img: feature1,
  },
  {
    title: "Smart Courses",
    desc: "Access curated courses from top platforms aligned with your learning objectives and career goals.",
    href: "/courses",
    img: feature2,
  },
  {
    title: "DSA Practice",
    desc: "Master data structures and algorithms with curated problems and company-wise questions.",
    href: "/dsa",
    img: feature3,
  },
  {
    title: "AI Doubt Resolution",
    desc: "Get instant clarifications on complex topics through intelligent AI-powered chat and guided support.",
    href: "/doubts",
    img: feature4,
  },
  {
    title: "Mind Refresh Games",
    desc: "Take productive breaks with brain-training games to keep your mind sharp, focused, and energized.",
    href: "/games",
    img: feature5,
  },
  {
    title: "More Features Coming",
    desc: "Hackathon listings, coding competitions, project showcases, and community events - Stay tuned!",
    href: "#",
    img: feature6,
    isComingSoon: true,
  },
];

const howItWorks = [
  {
    step: "01",
    title: "Sign Up",
    description:
      "Create your account and tell us about your learning objectives and career aspirations.",
    icon: Target,
  },
  {
    step: "02",
    title: "AI Roadmap",
    description:
      "Receive a personalized learning path generated by AI based on your goals and skill level.",
    icon: Rocket,
  },
  {
    step: "03",
    title: "Learn & Practice",
    description:
      "Access curated courses, solve DSA problems, and clear doubts with AI assistance.",
    icon: Code,
  },
  {
    step: "04",
    title: "Track Progress",
    description:
      "Monitor your growth, earn achievements, and stay motivated on your learning journey.",
    icon: TrendingUp,
  },
];

const stats = [
  { value: "12,19,773+", label: "Active Learners" },
  { value: "500+", label: "DSA Problems" },
  { value: "1000+", label: "Curated Courses" },
  { value: "24/7", label: "AI Support" },
];

const benefits = [
  {
    icon: CheckCircle,
    title: "Personalized Learning",
    desc: "AI-generated roadmaps tailored to your goals and experience level",
  },
  {
    icon: Code,
    title: "Comprehensive DSA",
    desc: "500+ curated problems with company-specific question sets",
  },
  {
    icon: Award,
    title: "Expert Resources",
    desc: "Access to top-rated courses from YouTube and premium platforms",
  },
  {
    icon: Users,
    title: "Community Support",
    desc: "Join thousands of learners on their journey to success",
  },
];

const testimonials = [
  {
    name: "RAHUL",
    role: "Software Engineer",
    text: "The AI roadmap feature is game-changing! It helped me land my dream job.",
  },
  {
    name: "SWAMY",
    role: "Full Stack Developer",
    text: "DSA practice with company-wise questions prepared me perfectly for interviews.",
  },
  {
    name: "SIVA",
    role: "Data Scientist",
    text: "The doubt resolution feature is incredible. I get answers instantly!",
  },
  {
    name: "Govind",
    role: "Data Analyst",
    text: "The curated courses saved me so much time searching for quality content.",
  },
];

export default function Home() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [currentTestimonial, setCurrentTestimonial] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">

      {/* BACKGROUND FLOATING ICONS */}
      <div className="absolute top-32 left-4 sm:top-48 sm:left-20 text-orange-400 text-xl sm:text-3xl animate-pulse">✦</div>
      <div className="absolute top-64 right-8 sm:top-80 sm:right-32 text-yellow-400 text-lg sm:text-2xl animate-pulse">✦</div>
      <div className="absolute top-80 left-1/4 sm:top-96 text-orange-400 text-base sm:text-xl animate-pulse">+</div>
      <div className="absolute bottom-32 right-4 sm:bottom-96 sm:right-20 text-yellow-400 text-lg sm:text-2xl animate-pulse">+</div>

      <Header />

      <main className="px-4 sm:px-5 py-8 sm:py-16 max-w-7xl mx-auto relative z-10">

        {/* HERO SECTION */}
        <section className="text-center mb-12 sm:mb-20 max-w-4xl mx-auto animate-fadeIn">
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold mb-5">
            Welcome{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400 animate-pulse">
              {user ? user.name.split(" ")[0].toUpperCase() : "Buddy"}
            </span>
          </h1>

          <p className="text-lg sm:text-xl md:text-2xl text-gray-400 mb-8 max-w-3xl mx-auto">
            Welcome to TrackWise Academy! You can call me ASM, your AI Skill Mentor—that's my special name.
            I'm here to help you master your skills with a unique AI-powered platform that guides your learning journey, answers your doubts, and keeps your mind sharp and motivated.
          </p>

          <Button
            variant="gradient"
            className="min-w-[240px] text-lg font-bold px-8 py-4 rounded-xl"
            onClick={() => navigate("/roadmaps")}
          >
            Let's start your journey
          </Button>
        </section>

        {/* HOW IT WORKS */}
<section className="mb-20">
  <div className="text-center mb-12">
    <h2 className="text-4xl font-extrabold mb-3">How It Works</h2>
    <p className="text-gray-400">Get started in just 4 simple steps</p>
  </div>

  <div className="relative flex flex-col md:flex-row items-center justify-center gap-10">

    {/* Dotted Path */}
    <div className="hidden md:block absolute top-1/2 left-0 w-full pointer-events-none -z-10">
      <svg width="100%" height="40">
        <line
          x1="5%"
          y1="20"
          x2="95%"
          y2="20"
          stroke="rgba(255,255,255,0.4)"
          strokeWidth="3"
          strokeDasharray="6 10"
        />
      </svg>
    </div>

    {howItWorks.map((item, index) => (
      <div
        key={index}
        className="bg-gray-900/50 backdrop-blur-sm rounded-2xl p-8 md:p-10 border border-gray-800 w-72 h-64 flex flex-col items-center justify-start text-center shadow-lg gap-3"
      >
        {/* STEP NUMBER */}
        <div className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">
          {index + 1}
        </div>

        {/* TITLE */}
        <h3 className="text-xl font-bold text-white">{item.title}</h3>

        {/* DESCRIPTION */}
        <p className="text-gray-300 text-sm leading-relaxed px-2">
          {item.description}
        </p>
      </div>
    ))}
  </div>
</section>


        {/* FEATURES (NOW USING FEATURECARD COMPONENT ⭐) */}
        <section className="mb-16 sm:mb-24">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold mb-4">
              Start Your Career Journey Today
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto">
              Comprehensive learning platform with AI-powered features
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 px-2 sm:px-0">
            {features.map((f, index) => (
              <FeatureCard
                key={index}
                title={f.title}
                desc={f.desc}
                img={f.img}
                onClick={() => navigate(f.href)}
                isComingSoon={f.isComingSoon}
              />
            ))}
          </div>
        </section>

        {/* BENEFITS */}
        <section className="mb-16 sm:mb-24">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold mb-4">
              Why Choose ASM?
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto">
              Features that set us apart from traditional learning platforms
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {benefits.map((benefit, index) => {
              const IconComponent = benefit.icon;
              return (
                <div
                  key={index}
                  className="flex gap-6 items-start bg-gray-900/50 backdrop-blur-sm rounded-2xl p-8 border border-gray-800 hover:border-orange-500/50 transition-all"
                >
                  <div className="flex-shrink-0">
                    <div className="w-14 h-14 bg-gradient-to-br from-purple-500/10 rounded-xl flex items-center justify-center">
                      <IconComponent className="w-7 h-7 text-purple-400" />
                    </div>
                  </div>

                  <div>
                    <h3 className="text-xl font-bold mb-2 text-white">{benefit.title}</h3>
                    <p className="text-gray-400 leading-relaxed">{benefit.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* TESTIMONIALS */}
        <section className="mb-16 sm:mb-24">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold mb-4">
              Success Stories
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto">
              Join thousands who have transformed their careers with ASM
            </p>
          </div>

          <div className="max-w-3xl mx-auto">
            <div className="bg-gray-900/50 backdrop-blur-sm rounded-2xl p-8 md:p-12 border border-gray-800 relative">
              <div className="text-6xl text-orange-400/20 absolute top-4 left-4">"</div>

              <div className="relative z-10">
                <p className="text-xl text-gray-300 mb-6 italic leading-relaxed">
                  {testimonials[currentTestimonial].text}
                </p>

                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-xl font-bold">
                    {testimonials[currentTestimonial].name[0]}
                  </div>

                  <div>
                    <div className="font-bold text-white">
                      {testimonials[currentTestimonial].name}
                    </div>
                    <div className="text-sm text-gray-400">
                      {testimonials[currentTestimonial].role}
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex justify-center gap-2 mt-8">
                {testimonials.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => setCurrentTestimonial(index)}
                    className={`h-2 rounded-full transition-all ${index === currentTestimonial
                        ? "bg-orange-500 w-8"
                        : "bg-gray-600 w-2"
                      }`}
                  />
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* CTA SECTION - UNIQUE DESIGN */}
        <section className="mb-16 sm:mb-24 relative">
          <div className="relative bg-gray-900/50 backdrop-blur-sm rounded-3xl p-8 md:p-12 border border-gray-800 overflow-hidden">
            
            {/* Content */}
            <div className="relative z-10">
              <div className="text-center mb-8">
                <div className="inline-flex items-center gap-2 px-4 py-2 bg-orange-500/10 border border-orange-500/20 rounded-full mb-4">
                  <span className="w-2 h-2 bg-orange-500 rounded-full animate-pulse"></span>
                  <span className="text-orange-400 text-sm font-medium">1.2M+ Active Learners</span>
                </div>
                
                <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold mb-4 bg-gradient-to-r from-white via-gray-100 to-gray-300 bg-clip-text text-transparent">
                  Ready to Start Your Journey?
                </h2>
                
                <p className="text-lg text-gray-300 mb-2 max-w-2xl mx-auto">
                  Join thousands of learners who are already mastering their skills
                </p>
                <p className="text-sm text-gray-400 max-w-xl mx-auto">
                  Start with a personalized roadmap, practice DSA, or explore curated courses
                </p>
              </div>

              {/* CTA Buttons with Stats */}
              <div className="flex flex-col sm:flex-row gap-6 justify-center items-center max-w-3xl mx-auto">
                <div className="flex flex-col items-center gap-3 w-full sm:w-auto">
                  <Button
                    variant="gradient"
                    className="w-full sm:w-auto min-w-[220px] text-base font-semibold px-8 py-3 shadow-lg shadow-orange-500/20 hover:shadow-orange-500/40 transition-all duration-300"
                    onClick={() => navigate(user ? "/roadmaps" : "/register")}
                  >
                    {user ? "Create Roadmap" : "Get Started Free"} →
                  </Button>
                  <span className="text-xs text-gray-500">Everything is Free of Cost</span>
                </div>

                <div className="hidden sm:block w-px h-16 bg-gray-700"></div>
                <div className="block sm:hidden w-16 h-px bg-gray-700"></div>

                <div className="flex flex-col items-center gap-3 w-full sm:w-auto">
                  <Button
                    variant="outline"
                    className="w-full sm:w-auto min-w-[220px] text-base font-semibold px-8 py-3 hover:bg-gray-800/50 transition-all duration-300"
                    onClick={() => navigate("/dsa")}
                  >
                    Explore DSA Problems
                  </Button>
                  <span className="text-xs text-gray-500">500+ curated problems</span>
                </div>
              </div>

              {/* Trust Indicators */}
              <div className="mt-10 pt-8 border-t border-gray-800/50">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
                  <div>
                    <div className="text-2xl font-bold text-white mb-1">1.2M+</div>
                    <div className="text-xs text-gray-400">Active Users</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-white mb-1">500+</div>
                    <div className="text-xs text-gray-400">DSA Problems</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-white mb-1">1000+</div>
                    <div className="text-xs text-gray-400">Courses</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-white mb-1">24/7</div>
                    <div className="text-xs text-gray-400">AI Support</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </main>

      {/* FOOTER */}
      <footer className="bg-[#181e24] border-t border-gray-800 pt-10 pb-4 text-gray-300 mt-10">
        <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row gap-10 md:gap-20 items-start">

          <div className="md:w-1/3">
            <h3 className="text-2xl font-bold mb-2">
              <span className="text-orange-400">ASM</span> AI Skill Mentor
            </h3>

            <p className="text-gray-400 mb-6 text-sm">
              Your AI-powered companion for mastering programming, DSA, and technical skills. Build roadmaps, solve problems, and achieve your career goals.
            </p>

            <div className="flex gap-4 text-gray-400">
              <a href="https://github.com/PalaniRahulDravid" target="_blank" rel="noopener noreferrer" className="hover:text-black">
                <Github size={22} />
              </a>
              <a href="https://www.linkedin.com/in/palani-rahul-dravid-a89916292/" target="_blank" rel="noopener noreferrer" className="hover:text-blue-600">
                <Linkedin size={22} />
              </a>
              <a href="https://www.instagram.com/useless._.boy._.rahul/" target="_blank" rel="noopener noreferrer" className="hover:text-red-500">
                <Instagram size={22} />
              </a>
              <a href="https://wa.me/9059074389" target="_blank" rel="noopener noreferrer" className="hover:text-green-400">
                <FaWhatsapp size={22} />
              </a>
            </div>
          </div>

          {/* Footer Columns */}
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4 w-full text-sm">

            <div>
              <p className="text-orange-400 font-semibold mb-3">Features</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2" onClick={() => navigate("/roadmaps")}>
                AI Roadmaps
              </p>
              <p className="hover:text-orange-400 cursor-pointer mb-2" onClick={() => navigate("/courses")}>
                Smart Courses
              </p>
              <p className="hover:text-orange-400 cursor-pointer mb-2" onClick={() => navigate("/dsa")}>
                DSA Practice
              </p>
            </div>

            <div>
              <p className="text-orange-400 font-semibold mb-3">Resources</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2" onClick={() => navigate("/doubts")}>
                Doubt Resolution
              </p>
              <p className="hover:text-orange-400 cursor-pointer mb-2" onClick={() => navigate("/games")}>
                Mind Games
              </p>
            </div>

            <div>
              <p className="text-orange-400 font-semibold mb-3">Company</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2">About Us</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2">Contact</p>
            </div>

            <div>
              <p className="text-orange-400 font-semibold mb-3">Legal</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2">Privacy Policy</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2">Terms of Service</p>
            </div>

          </div>
        </div>

        <div className="text-center mt-8 border-t border-gray-800 pt-4 text-xs text-gray-500">
          © 2025 TrackWise Academy | All rights reserved. Built with by Rahul Dravid.
        </div>
      </footer>
    </div>
  );
}
