import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Header from "../components/Header";
import Button from "../components/Button";
import FeatureCard from "../components/FeatureCard";
import useAuth from "../hooks/useAuth";
import {
  Github, Linkedin, Instagram, Code,
  Target,
  Rocket,
  TrendingUp,
  CheckCircle,
  Award,
  Users,
  BookOpen,
  MessageCircleQuestion,
  Gamepad2,
  RouteIcon,
  GraduationCap,
  Sparkles,
} from "lucide-react";
import { FaWhatsapp } from "react-icons/fa";

// IMPORT IMAGES
import feature1 from "../assets/featurecard1.png";
import feature2 from "../assets/featurecard2.png";
import feature3 from "../assets/featurecard3.png";
import feature4 from "../assets/featurecard4.png";
import feature5 from "../assets/featurecard5.png";
import feature6 from "../assets/featurecard6.png";

const features = [
  {
    title: "AI Roadmap Generator",
    desc: "Build your personalized learning path with powerful AI assistance crafted for your long-term career goals.",
    href: "/roadmaps",
    img: feature1,
  },
  {
    title: "Smart Courses",
    desc: "Access curated courses from top platforms aligned with your learning objectives and career goals.",
    href: "/courses",
    img: feature2,
  },
  {
    title: "DSA Practice",
    desc: "Master data structures and algorithms with curated problems and company-wise questions.",
    href: "/dsa",
    img: feature3,
  },
  {
    title: "AI Doubt Resolution",
    desc: "Get instant clarifications on complex topics through intelligent AI-powered chat and guided support.",
    href: "/doubts",
    img: feature4,
  },
  {
    title: "Mind Refresh Games",
    desc: "Take productive breaks with brain-training games to keep your mind sharp, focused, and energized.",
    href: "/games",
    img: feature5,
  },
  {
    title: "More Features Coming",
    desc: "Hackathon listings, coding competitions, project showcases, and community events - Stay tuned!",
    href: "#",
    img: feature6,
    isComingSoon: true,
  },
];

const howItWorks = [
  {
    step: "01",
    title: "Sign Up",
    description:
      "Create your account and tell us about your learning objectives and career aspirations.",
    icon: Target,
  },
  {
    step: "02",
    title: "AI Roadmap",
    description:
      "Receive a personalized learning path generated by AI based on your goals and skill level.",
    icon: Rocket,
  },
  {
    step: "03",
    title: "Learn & Practice",
    description:
      "Access curated courses, solve DSA problems, and clear doubts with AI assistance.",
    icon: Code,
  },
  {
    step: "04",
    title: "Track Progress",
    description:
      "Monitor your growth, earn achievements, and stay motivated on your learning journey.",
    icon: TrendingUp,
  },
];

const stats = [
  { value: "12,19,773+", label: "Active Learners" },
  { value: "500+", label: "DSA Problems" },
  { value: "1000+", label: "Curated Courses" },
  { value: "24/7", label: "AI Support" },
];

const benefits = [
  {
    icon: CheckCircle,
    title: "Personalized Learning",
    desc: "AI-generated roadmaps tailored to your goals and experience level",
  },
  {
    icon: Code,
    title: "Comprehensive DSA",
    desc: "500+ curated problems with company-specific question sets",
  },
  {
    icon: Award,
    title: "Expert Resources",
    desc: "Access to top-rated courses from YouTube and premium platforms",
  },
  {
    icon: Users,
    title: "Community Support",
    desc: "Join thousands of learners on their journey to success",
  },
];

const testimonials = [
  {
    name: "RAHUL",
    role: "Software Engineer",
    text: "The AI roadmap feature is game-changing! It helped me land my dream job.",
  },
  {
    name: "SWAMY",
    role: "Full Stack Developer",
    text: "DSA practice with company-wise questions prepared me perfectly for interviews.",
  },
  {
    name: "SIVA",
    role: "Data Scientist",
    text: "The doubt resolution feature is incredible. I get answers instantly!",
  },
  {
    name: "Govind",
    role: "Data Analyst",
    text: "The curated courses saved me so much time searching for quality content.",
  },
];

export default function Home() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [currentTestimonial, setCurrentTestimonial] = useState(0);
  const [stats, setStats] = useState({
    users: 0,
    dsaProblems: 0,
    courses: 0
  });
  const [recentUsers, setRecentUsers] = useState([]);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => {
    // Fetch real platform stats from backend
    const fetchPlatformStats = async () => {
      try {
        const apiUrl = import.meta.env.VITE_API_URL || 'https://trackwise-academy.onrender.com/api';
        const response = await fetch(`${apiUrl}/auth/platform-stats`, {
          credentials: 'include'
        });
        const data = await response.json();
        if (data.success) {
          setStats({
            users: data.data.users,
            dsaProblems: data.data.dsaProblems,
            courses: data.data.courses
          });
        }
      } catch (error) {
        console.error('Failed to fetch platform stats:', error);
        // Set fallback values on error
        setStats({
          users: 0,
          dsaProblems: 500,
          courses: 1000
        });
      }
    };
    fetchPlatformStats();
  }, []);

  useEffect(() => {
    // Fetch recent 5 users from backend
    const fetchRecentUsers = async () => {
      try {
        const apiUrl = import.meta.env.VITE_API_URL || 'https://trackwise-academy.onrender.com/api';
        const response = await fetch(`${apiUrl}/auth/recent-users`, {
          credentials: 'include'
        });
        const data = await response.json();
        if (data.success && data.data.users.length > 0) {
          setRecentUsers(data.data.users);
        }
      } catch (error) {
        console.error('Failed to fetch recent users:', error);
        // Keep empty array as fallback
        setRecentUsers([]);
      }
    };
    fetchRecentUsers();
  }, []);

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white relative overflow-hidden" role="main" aria-label="AI Skill Mentor - Home Page">

      <Header />

      <main className="relative z-10 pt-[40px]">

        {/* HERO SECTION - FUTURISTIC AI DESIGN */}
        {/* HERO SECTION - GCORE STYLE CIRCUIT BOARD DESIGN */}
<section className="relative overflow-hidden min-h-[calc(100vh-72px)] flex flex-col items-center justify-center py-6 sm:py-8">
  
  {/* Dark Background */}
  <div className="absolute inset-0 bg-[#0a0a0a]"></div>
  
  {/* Mobile Orange Gradient - Half Screen */}
  <div className="block sm:hidden absolute top-0 left-0 right-0 h-1/2 bg-gradient-to-b from-orange-500/20 via-orange-600/10 to-transparent"></div>
  
  {/* Orange Light Streak from Top Right - Desktop only */}
  <div className="hidden sm:block absolute top-0 right-0 w-[600px] h-[600px] bg-gradient-to-bl from-orange-500/30 via-orange-600/10 to-transparent blur-3xl"></div>
  <div className="hidden sm:block absolute top-0 right-1/4 w-[400px] h-[300px] bg-gradient-to-b from-orange-500/20 via-orange-400/5 to-transparent blur-2xl transform rotate-45"></div>
  
  {/* Subtle Grid Pattern */}
  <div className="absolute inset-0 bg-[linear-gradient(to_right,#1a1a1a_1px,transparent_1px),linear-gradient(to_bottom,#1a1a1a_1px,transparent_1px)] bg-[size:80px_80px] opacity-20"></div>
  
  {/* TOP SECTION - TEXT CONTENT */}
  <div className="container relative mx-auto px-4 z-20 flex-shrink-0 mb-0 sm:mb-[-90px]">
    <div className="max-w-4xl mx-auto text-center space-y-2.5 sm:space-y-2.5">
      
      {/* Badge */}
      <div className="flex justify-center animate-fadeIn mb-0 sm:mb-0">
        <div className="inline-flex items-center gap-2 px-4 py-2 sm:px-4 sm:py-2 bg-[#1a1a1a]/95 backdrop-blur-sm border-2 border-orange-500/50 rounded-full shadow-[0_4px_12px_rgba(0,0,0,0.5)]">
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-500 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
          </span>
          <span className="text-xs sm:text-sm font-medium text-orange-400">
            Your Complete AI Learning Platform
          </span>
        </div>
      </div>
      
      {/* Main Heading */}
      <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight leading-tight animate-fadeIn delay-100 px-2 mt-2 sm:mt-0">
        <span className="block text-white">Your AI-Powered Tech Journey</span>
      </h1>
      
      {/* Description */}
      <p className="text-sm sm:text-base md:text-lg text-gray-300 max-w-2xl mx-auto leading-relaxed animate-fadeIn delay-200 px-4 mt-2 sm:mt-0">
        Boost your learning efficiency globally by bringing AI-powered education closer to you. Enjoy personalized roadmaps and best-in-class learning experience.
      </p>
      
      {/* CTA Buttons */}
      <div className="flex flex-col sm:flex-row gap-3 justify-center pt-3 sm:pt-2 animate-fadeIn delay-300 px-4">
        <button
          onClick={() => navigate("/roadmaps")}
          className="relative z-30 group inline-flex items-center justify-center gap-2 px-8 sm:px-10 py-3.5 bg-orange-500 hover:bg-orange-600 text-white font-semibold rounded-lg transition-all duration-200 hover:shadow-lg hover:shadow-orange-500/30 text-sm cursor-pointer shadow-lg"
        >
          Get Started
        </button>
        <button
          onClick={() => {
            const featuresSection = document.querySelector('[data-section="features"]');
            if (featuresSection) {
              featuresSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
          }}
          className="relative z-30 inline-flex items-center justify-center gap-2 px-5 py-3.5 bg-transparent hover:bg-gray-800/50 text-white font-semibold border-2 border-gray-600 hover:border-gray-500 rounded-lg transition-all duration-200 text-sm cursor-pointer"
        >
          Explore Features
        </button>
      </div>
      
      {/* Recent Users Section - Mobile Only */}
      {recentUsers.length > 0 && (
        <div className="block sm:hidden mt-4 animate-fadeIn delay-400">
          <div className="flex flex-col items-center gap-2">
            <div className="flex -space-x-3">
              {recentUsers.slice(0, 5).map((user, index) => (
                <div
                  key={user._id || index}
                  className="relative w-10 h-10 rounded-full border-2 border-[#0a0a0a] shadow-lg overflow-hidden"
                  style={{ zIndex: 5 - index }}
                >
                  {user.profilePicture ? (
                    <img 
                      src={user.profilePicture} 
                      alt={user.name || 'User'} 
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="w-full h-full bg-gradient-to-br from-orange-400 to-pink-500 flex items-center justify-center text-white font-semibold text-sm">
                      {user.name ? user.name.charAt(0).toUpperCase() : 'U'}
                    </div>
                  )}
                </div>
              ))}
            </div>
            <p className="text-xs text-gray-400">
              Join our recent learners
            </p>
          </div>
        </div>
      )}
    </div>
  </div>

  {/* CIRCUIT BOARD ANIMATION SECTION - Hidden on mobile */}
  <div className="hidden sm:flex container relative mx-auto px-4 z-10 items-center justify-center flex-1 -mt-4">
    <div className="relative w-full max-w-6xl h-[280px] sm:h-[320px] md:h-[360px]">
      
      {/* SVG Circuit Lines with Light Animation */}
      <svg className="absolute inset-0 w-full h-full" viewBox="0 0 800 280" preserveAspectRatio="xMidYMid meet" style={{ overflow: 'visible' }}>
        <defs>
          {/* Glow Filter */}
          <filter id="circuitGlow" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
            <feMerge>
              <feMergeNode in="coloredBlur"/>
              <feMergeNode in="SourceGraphic"/>
            </feMerge>
          </filter>
          
          {/* Line Gradient */}
          <linearGradient id="lineGrad" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#f97316" stopOpacity="0.6"/>
            <stop offset="100%" stopColor="#f97316" stopOpacity="0.2"/>
          </linearGradient>
        </defs>
        
        {/* LEFT TOP LINE - Target Icon */}
        <path 
          d="M 70 40 L 70 110 L 378 110 L 378 140" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="3s" repeatCount="indefinite">
            <mpath href="#leftTopPath" />
          </animateMotion>
        </circle>
        <path id="leftTopPath" d="M 70 40 L 70 110 L 378 110 L 378 140" fill="none" className="hidden sm:block"/>
        
        {/* LEFT MIDDLE LINE - Code Icon */}
        <path 
          d="M 70 140 L 378 140" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="2.5s" repeatCount="indefinite" begin="0.5s">
            <mpath href="#leftMidPath" />
          </animateMotion>
        </circle>
        <path id="leftMidPath" d="M 70 140 L 378 140" fill="none" className="hidden sm:block"/>
        
        {/* LEFT BOTTOM LINE - Rocket Icon */}
        <path 
          d="M 70 240 L 70 170 L 378 170 L 378 140" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="3.5s" repeatCount="indefinite" begin="1s">
            <mpath href="#leftBottomPath" />
          </animateMotion>
        </circle>
        <path id="leftBottomPath" d="M 70 240 L 70 170 L 378 170 L 378 140" fill="none" className="hidden sm:block"/>
        
        {/* RIGHT TOP LINE */}
        <path 
          d="M 730 40 L 730 110 L 422 110 L 422 140" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="3s" repeatCount="indefinite" begin="0.3s">
            <mpath href="#rightTopPath" />
          </animateMotion>
        </circle>
        <path id="rightTopPath" d="M 730 40 L 730 110 L 422 110 L 422 140" fill="none" className="hidden sm:block"/>
        
        {/* RIGHT MIDDLE LINE */}
        <path 
          d="M 730 140 L 422 140" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="2.5s" repeatCount="indefinite" begin="0.8s">
            <mpath href="#rightMidPath" />
          </animateMotion>
        </circle>
        <path id="rightMidPath" d="M 730 140 L 422 140" fill="none" className="hidden sm:block"/>
        
        {/* RIGHT BOTTOM LINE */}
        <path 
          d="M 730 240 L 730 170 L 422 170 L 422 140" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="3.5s" repeatCount="indefinite" begin="1.3s">
            <mpath href="#rightBottomPath" />
          </animateMotion>
        </circle>
        <path id="rightBottomPath" d="M 730 240 L 730 170 L 422 170 L 422 140" fill="none" className="hidden sm:block"/>
        
        {/* BOTTOM CENTER LINE */}
        <path 
          d="M 400 260 L 400 170" 
          stroke="#f97316" 
          strokeWidth="2" 
          strokeOpacity="0.3" 
          fill="none"
          className="hidden sm:block"
        />
        <circle r="4" fill="#f97316" filter="url(#circuitGlow)" className="hidden sm:block">
          <animateMotion dur="2s" repeatCount="indefinite" begin="0.2s">
            <mpath href="#bottomPath" />
          </animateMotion>
        </circle>
        <path id="bottomPath" d="M 400 260 L 400 170" fill="none" className="hidden sm:block"/>
      </svg>
      
      {/* LEFT SIDE FEATURE BOXES */}
      <div className="absolute left-2 sm:left-6 md:left-8 lg:left-10 top-1/2 -translate-y-1/2 flex flex-col gap-[100px]">
        {/* AI Roadmap */}
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <RouteIcon className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
        
        {/* DSA Practice */}
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <Code className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
        
        {/* Training/Courses */}
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <GraduationCap className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
      </div>
      
      {/* CENTER AI CHIP - SMALLER */}
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
        <div className="relative w-20 h-20 sm:w-24 sm:h-24">
          {/* Chip Base */}
          <div className="absolute inset-0 bg-[#1a1a1a] rounded-2xl border border-gray-600"></div>
          
          {/* Chip Pins - Top */}
          <div className="absolute -top-2 left-1/2 -translate-x-1/2 flex gap-1">
            <div className="w-1 h-2 bg-orange-500/60 rounded-sm"></div>
            <div className="w-1 h-2 bg-orange-500/60 rounded-sm"></div>
            <div className="w-1 h-2 bg-orange-500/60 rounded-sm"></div>
          </div>
          
          {/* Chip Pins - Bottom */}
          <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 flex gap-1">
            <div className="w-1 h-2 bg-orange-500/60 rounded-sm"></div>
            <div className="w-1 h-2 bg-orange-500/60 rounded-sm"></div>
            <div className="w-1 h-2 bg-orange-500/60 rounded-sm"></div>
          </div>
          
          {/* Chip Pins - Left */}
          <div className="absolute left-[-8px] top-1/2 -translate-y-1/2 flex flex-col gap-1">
            <div className="w-2 h-1 bg-orange-500/60 rounded-sm"></div>
            <div className="w-2 h-1 bg-orange-500/60 rounded-sm"></div>
            <div className="w-2 h-1 bg-orange-500/60 rounded-sm"></div>
          </div>
          
          {/* Chip Pins - Right */}
          <div className="absolute right-[-8px] top-1/2 -translate-y-1/2 flex flex-col gap-1">
            <div className="w-2 h-1 bg-orange-500/60 rounded-sm"></div>
            <div className="w-2 h-1 bg-orange-500/60 rounded-sm"></div>
            <div className="w-2 h-1 bg-orange-500/60 rounded-sm"></div>
          </div>
          
          {/* Inner Chip with AI Text */}
          <div className="absolute inset-2 bg-[#0a0a0a] rounded-xl border border-gray-700 flex items-center justify-center">
            <span className="text-xl sm:text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-br from-gray-300 to-gray-500" style={{ fontFamily: 'Poppins, sans-serif' }}>
              AI
            </span>
          </div>
        </div>
      </div>
      
      {/* RIGHT SIDE FEATURE BOXES */}
      <div className="absolute right-2 sm:right-6 md:right-8 lg:right-10 top-1/2 -translate-y-1/2 flex flex-col gap-[100px]">
        {/* Doubt Resolution */}
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <MessageCircleQuestion className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
        
        {/* Mind Games */}
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <Gamepad2 className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
        
        {/* More Features */}
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <Sparkles className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
      </div>
      
      {/* BOTTOM CENTER BOX */}
      <div className="absolute bottom-0 left-1/2 -translate-x-1/2">
        <div className="w-10 h-10 sm:w-12 sm:h-12 bg-[#1a1a1a] rounded-xl border border-gray-700 flex items-center justify-center cursor-pointer hover:border-orange-500/50 hover:shadow-[0_0_20px_rgba(249,115,22,0.3)] transition-all duration-300 group">
          <Users className="w-5 h-5 sm:w-6 sm:h-6 text-gray-400 group-hover:text-orange-400 transition-colors" />
        </div>
      </div>
      
    </div>
  </div>

  {/* Stats at Bottom */}
  {stats.users > 0 && (
    <div className="container relative mx-auto px-4 z-20 flex justify-center mt-4 sm:mt-4 animate-fadeIn delay-500">
      <div className="inline-flex items-center gap-2 px-4 py-2 sm:px-4 sm:py-2 rounded-full bg-[#1a1a1a]/95 backdrop-blur-sm border-2 border-gray-700 shadow-[0_4px_12px_rgba(0,0,0,0.5)]">
        <Users className="h-4 w-4 sm:h-4 sm:w-4 text-orange-400" />
        <span className="text-xs sm:text-sm text-gray-200 font-medium">
          Join <span className="text-orange-400 font-bold">{stats.users.toLocaleString()}+</span> developers already learning
        </span>
      </div>
    </div>
  )}
</section>


        <div className="max-w-7xl mx-auto px-4">

        {/* HOW IT WORKS */}
<section className="mb-16 sm:mb-20 pt-12 sm:pt-16" aria-labelledby="how-it-works-heading">
  <div className="text-center mb-12 sm:mb-16 px-4">
    <h2 id="how-it-works-heading" className="text-2xl sm:text-3xl md:text-4xl font-extrabold mb-3 sm:mb-4">How It Works</h2>
    <p className="text-gray-400 text-sm sm:text-base md:text-lg">Get started in just 4 simple steps</p>
  </div>

  <div className="relative grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 md:gap-8 lg:gap-6 px-4">

    {/* Dotted Path */}
    <div className="hidden lg:block absolute top-1/2 left-0 w-full pointer-events-none -z-10">
      <svg width="100%" height="40">
        <line
          x1="5%"
          y1="20"
          x2="95%"
          y2="20"
          stroke="rgba(255,255,255,0.4)"
          strokeWidth="3"
          strokeDasharray="6 10"
        />
      </svg>
    </div>

    {howItWorks.map((item, index) => (
      <div
        key={index}
        className="bg-gray-900/50 backdrop-blur-sm rounded-lg p-6 sm:p-8 border border-gray-800 w-full min-h-[240px] sm:min-h-[260px] lg:h-64 flex flex-col items-center justify-start text-center shadow-lg gap-2 sm:gap-3"
      >
        {/* STEP NUMBER */}
        <div className="text-3xl sm:text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">
          {index + 1}
        </div>

        {/* TITLE */}
        <h3 className="text-lg sm:text-xl font-bold text-white">{item.title}</h3>

        {/* DESCRIPTION */}
        <p className="text-gray-300 text-xs sm:text-sm leading-relaxed px-1 sm:px-2">
          {item.description}
        </p>
      </div>
    ))}
  </div>
</section>


        {/* FEATURES (NOW USING FEATURECARD COMPONENT ⭐) */}
        <section className="mb-16 sm:mb-24 px-4" data-section="features">
          <div className="text-center mb-10 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-extrabold mb-3 sm:mb-4">
              Start Your Career Journey Today
            </h2>
            <p className="text-sm sm:text-base md:text-lg text-gray-400 max-w-2xl mx-auto px-4">
              Comprehensive learning platform with AI-powered features
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8 max-w-7xl mx-auto">
            {features.map((f, index) => (
              <FeatureCard
                key={index}
                title={f.title}
                desc={f.desc}
                img={f.img}
                onClick={() => navigate(f.href)}
                isComingSoon={f.isComingSoon}
              />
            ))}
          </div>
        </section>

        {/* BENEFITS */}
        <section className="mb-16 sm:mb-24 px-4">
          <div className="text-center mb-10 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-extrabold mb-3 sm:mb-4">
              Why Choose ASM?
            </h2>
            <p className="text-sm sm:text-base md:text-lg text-gray-400 max-w-2xl mx-auto px-4">
              Features that set us apart from traditional learning platforms
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-8 max-w-6xl mx-auto">
            {benefits.map((benefit, index) => {
              const IconComponent = benefit.icon;
              return (
                <div
                  key={index}
                  className="flex gap-4 sm:gap-6 items-start bg-gray-900/50 backdrop-blur-sm rounded-lg p-5 sm:p-6 md:p-8 border border-gray-800 hover:border-orange-500/50 transition-all"
                >
                  <div className="flex-shrink-0">
                    <div className="w-12 h-12 sm:w-14 sm:h-14 bg-gradient-to-br from-purple-500/10 rounded-lg flex items-center justify-center">
                      <IconComponent className="w-6 h-6 sm:w-7 sm:h-7 text-purple-400" />
                    </div>
                  </div>

                  <div className="flex-1 min-w-0">
                    <h3 className="text-lg sm:text-xl font-bold mb-2 text-white">{benefit.title}</h3>
                    <p className="text-sm sm:text-base text-gray-400 leading-relaxed">{benefit.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* TESTIMONIALS */}
        <section className="mb-16 sm:mb-24 px-4">
          <div className="text-center mb-10 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-extrabold mb-3 sm:mb-4">
              Success Stories
            </h2>
            <p className="text-sm sm:text-base md:text-lg text-gray-400 max-w-2xl mx-auto px-4">
              Join thousands who have transformed their careers with ASM
            </p>
          </div>

          <div className="max-w-3xl mx-auto">
            <div className="bg-gray-900/50 backdrop-blur-sm rounded-lg p-6 sm:p-8 md:p-12 border border-gray-800 relative">
              <div className="text-4xl sm:text-5xl md:text-6xl text-orange-400/20 absolute top-3 sm:top-4 left-3 sm:left-4">"</div>

              <div className="relative z-10">
                <p className="text-base sm:text-lg md:text-xl text-gray-300 mb-5 sm:mb-6 italic leading-relaxed">
                  {testimonials[currentTestimonial].text}
                </p>

                <div className="flex items-center gap-3 sm:gap-4">
                  <div className="w-10 h-10 sm:w-12 sm:h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-lg sm:text-xl font-bold flex-shrink-0">
                    {testimonials[currentTestimonial].name[0]}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="font-bold text-white text-sm sm:text-base">
                      {testimonials[currentTestimonial].name}
                    </div>
                    <div className="text-xs sm:text-sm text-gray-400">
                      {testimonials[currentTestimonial].role}
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex justify-center gap-2 mt-8">
                {testimonials.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => setCurrentTestimonial(index)}
                    className={`h-2 rounded-full transition-all ${index === currentTestimonial
                        ? "bg-orange-500 w-8"
                        : "bg-gray-600 w-2"
                      }`}
                  />
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* CTA SECTION - UNIQUE DESIGN */}
        <section className="mb-16 sm:mb-24 relative px-4">
          <div className="relative bg-gray-900/50 backdrop-blur-sm rounded-lg p-6 sm:p-8 md:p-12 border border-gray-800 overflow-hidden">
            
            {/* Content */}
            <div className="relative z-10">
              <div className="text-center mb-6 sm:mb-8">
                <div className="inline-flex items-center gap-2 px-3 sm:px-4 py-1.5 sm:py-2 bg-orange-500/10 border border-orange-500/20 rounded-lg mb-3 sm:mb-4">
                  <span className="w-2 h-2 bg-orange-500 rounded-full animate-pulse"></span>
                  <span className="text-orange-400 text-xs sm:text-sm font-medium">{stats.users > 0 ? `${stats.users.toLocaleString()} Active Learners` : 'Join Our Growing Community'}</span>
                </div>
                
                <h2 className="text-2xl sm:text-3xl md:text-4xl font-extrabold mb-3 sm:mb-4 bg-gradient-to-r from-white via-gray-100 to-gray-300 bg-clip-text text-transparent px-2">
                  Ready to Start Your Journey?
                </h2>
                
                <p className="text-sm sm:text-base md:text-lg text-gray-300 mb-2 max-w-2xl mx-auto px-4">
                  Join thousands of learners who are already mastering their skills
                </p>
                <p className="text-xs sm:text-sm text-gray-400 max-w-xl mx-auto px-4">
                  Start with a personalized roadmap, practice DSA, or explore curated courses
                </p>
              </div>

              {/* CTA Buttons with Stats */}
              <div className="flex flex-col sm:flex-row gap-4 sm:gap-6 justify-center items-center max-w-3xl mx-auto">
                <div className="flex flex-col items-center gap-2 sm:gap-3 w-full sm:w-auto">
                  <Button
                    variant="gradient"
                    className="w-full sm:w-auto min-w-[200px] sm:min-w-[220px] text-sm sm:text-base font-semibold px-6 sm:px-8 py-2.5 sm:py-3 shadow-lg shadow-orange-500/20 hover:shadow-orange-500/40 transition-all duration-300"
                    onClick={() => navigate(user ? "/roadmaps" : "/register")}
                  >
                    {user ? "Create Roadmap" : "Get Started Free"} →
                  </Button>
                  <span className="text-xs text-gray-500">Everything is Free of Cost</span>
                </div>

                <div className="hidden sm:block w-px h-16 bg-gray-700"></div>
                <div className="block sm:hidden w-16 h-px bg-gray-700"></div>

                <div className="flex flex-col items-center gap-2 sm:gap-3 w-full sm:w-auto">
                  <Button
                    variant="outline"
                    className="w-full sm:w-auto min-w-[200px] sm:min-w-[220px] text-sm sm:text-base font-semibold px-6 sm:px-8 py-2.5 sm:py-3 hover:bg-gray-800/50 transition-all duration-300"
                    onClick={() => navigate("/dsa")}
                  >
                    Explore DSA Problems
                  </Button>
                  <span className="text-xs text-gray-500">500+ curated problems</span>
                </div>
              </div>

              {/* Trust Indicators */}
              <div className="mt-8 sm:mt-10 pt-6 sm:pt-8 border-t border-gray-800/50">
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6 text-center">
                  <div>
                    <div className="text-xl sm:text-2xl font-bold text-white mb-1">
                      {stats.users > 0 ? stats.users.toLocaleString() : '1000+'}
                    </div>
                    <div className="text-xs text-gray-400">Active Users</div>
                  </div>
                  <div>
                    <div className="text-xl sm:text-2xl font-bold text-white mb-1">
                      {stats.dsaProblems > 0 ? `${stats.dsaProblems}+` : '500+'}
                    </div>
                    <div className="text-xs text-gray-400">DSA Problems</div>
                  </div>
                  <div className="col-span-2 md:col-span-1">
                    <div className="text-xl sm:text-2xl font-bold text-white mb-1">
                      {stats.courses > 0 ? `${stats.courses.toLocaleString()}+` : '1000+'}
                    </div>
                    <div className="text-xs text-gray-400">Courses</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        </div>
      </main>

      {/* FOOTER */}
      <footer className="bg-[#181e24] border-t border-gray-800 pt-10 pb-4 text-gray-300 mt-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 flex flex-col lg:flex-row gap-10 lg:gap-20 items-start">

          <div className="lg:w-1/3">
            <h3 className="text-xl sm:text-2xl font-bold mb-2">
              <span className="text-orange-400">ASM</span> AI Skill Mentor
            </h3>

            <p className="text-gray-400 mb-6 text-xs sm:text-sm leading-relaxed">
              Your AI-powered companion for mastering programming, DSA, and technical skills. Build roadmaps, solve problems, and achieve your career goals.
            </p>

            <div className="flex gap-4 text-gray-400">
              <a href="https://github.com/PalaniRahulDravid" target="_blank" rel="noopener noreferrer" className="hover:text-black transition-colors">
                <Github size={20} className="sm:w-[22px] sm:h-[22px]" />
              </a>
              <a href="https://www.linkedin.com/in/palani-rahul-dravid-a89916292/" target="_blank" rel="noopener noreferrer" className="hover:text-blue-600 transition-colors">
                <Linkedin size={20} className="sm:w-[22px] sm:h-[22px]" />
              </a>
              <a href="https://www.instagram.com/useless._.boy._.rahul/" target="_blank" rel="noopener noreferrer" className="hover:text-red-500 transition-colors">
                <Instagram size={20} className="sm:w-[22px] sm:h-[22px]" />
              </a>
              <a href="https://wa.me/9059074389" target="_blank" rel="noopener noreferrer" className="hover:text-green-400 transition-colors">
                <FaWhatsapp size={20} className="sm:w-[22px] sm:h-[22px]" />
              </a>
            </div>
          </div>

          {/* Footer Columns */}
          <div className="grid grid-cols-2 gap-6 sm:gap-8 lg:grid-cols-4 w-full text-xs sm:text-sm">

            <div>
              <p className="text-orange-400 font-semibold mb-3 text-sm sm:text-base">Features</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors" onClick={() => navigate("/roadmaps")}>
                AI Roadmaps
              </p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors" onClick={() => navigate("/courses")}>
                Smart Courses
              </p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors" onClick={() => navigate("/dsa")}>
                DSA Practice
              </p>
            </div>

            <div>
              <p className="text-orange-400 font-semibold mb-3 text-sm sm:text-base">Resources</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors" onClick={() => navigate("/doubts")}>
                Doubt Resolution
              </p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors" onClick={() => navigate("/games")}>
                Mind Games
              </p>
            </div>

            <div>
              <p className="text-orange-400 font-semibold mb-3 text-sm sm:text-base">Company</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors">About Us</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors">Contact</p>
            </div>

            <div>
              <p className="text-orange-400 font-semibold mb-3 text-sm sm:text-base">Legal</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors">Privacy Policy</p>
              <p className="hover:text-orange-400 cursor-pointer mb-2 transition-colors">Terms of Service</p>
            </div>

          </div>
        </div>

        <div className="text-center mt-8 border-t border-gray-800 pt-4 text-xs text-gray-500">
          © 2025 TrackWise Academy | All rights reserved. Built with by Rahul Dravid.
        </div>
      </footer>
    </div>
  );
}
